### ISSUE TITLE
Repo's name, description and file names are a bit misleading

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/UCR-MapML-Matrix#28]
This repository's name is "UCR-MapML-Matrix", the description is "Hosts examples and documents how MapML fulfills the Use Cases and Requirements for Web Maps" and has file names such as `mapml-ucr.json`.

I think that is misleading because the document also shows how all the reviewed reference tools align with the use cases and capabilities, as defined in Use Cases and Requirements for Standardizing _Web Maps_ (i.e. not: Use Cases and Requirements for Standardizing _MapML_).

**Comment by prushforth** [comment]
The objective of the matrix is not to show how those libraries respond to the UCRs. In fact those libraries are used as examples of the capabilities, so not really a need to establish that they fulfill anything. What the UCR fulfillment matrix is supposed to do is establish to what degree (the) effort(s) to polyfill the Web Platform implementation of the UCRs do(es) that. I suppose there could be other efforts, but so far MapML and Web-Map-Custom-Element is all we've got

**Comment by Malvoz** [comment]
Oh, you mean the document does what it says it does?

> This document compares the capabilities of existing popular web mapping libraries, comparing and contrasting implementations with the MapML specification and the reference MapML-Viewer custom-component polyfill

Sorry, I'm the only one confused here 🤦🏼‍♂️
